pub mod clipboard;
pub mod clipper;
pub mod foreground;
pub mod jumpscare;
pub mod openurl;
pub mod print;
pub mod screenshot;
pub mod webcam;
pub mod audio;

pub use clipboard::ClipboardCommand;
pub use clipper::ClipperCommand;
pub use foreground::ForegroundCommand;
pub use jumpscare::JumpscareCommand;
pub use openurl::OpenUrlCommand;
pub use print::PrintCommand;
pub use screenshot::ScreenshotCommand;
pub use webcam::WebcamCommand;
pub use audio::AudioCommand;
